"""Player mmrs field

Revision ID: 1148065c6585
Revises: 3a6c66f5d5ac
Create Date: 2021-06-14 15:53:18.806017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1148065c6585'
down_revision = '3a6c66f5d5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('game_mmr', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'game_mmr')
    # ### end Alembic commands ###
