"""matches fix

Revision ID: 72d05acd57f6
Revises: 0adff68aa633
Create Date: 2020-01-13 03:13:58.415729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d05acd57f6'
down_revision = '0adff68aa633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('game', sa.String(length=48), nullable=True))
    with op.batch_alter_table('match') as batch_op:
        batch_op.drop_column('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('name', sa.VARCHAR(length=48), nullable=True))
    op.drop_column('match', 'game')
    # ### end Alembic commands ###
