"""main score field

Revision ID: 75bd616637c3
Revises: 1148065c6585
Create Date: 2021-06-14 16:57:29.249321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bd616637c3'
down_revision = '1148065c6585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('main_score_field', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'main_score_field')
    # ### end Alembic commands ###
