"""min players added

Revision ID: 75bd14b2026c
Revises: 941586c1203d
Create Date: 2021-06-14 14:52:13.538608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bd14b2026c'
down_revision = '941586c1203d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('g_id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('mmr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('g_id', 'p_id')
    )
    op.add_column('game', sa.Column('min_players', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'min_players')
    op.drop_table('skill')
    # ### end Alembic commands ###
