"""displayname

Revision ID: 86db8785f7a5
Revises: a728fec09205
Create Date: 2020-01-13 01:44:19.668248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86db8785f7a5'
down_revision = 'a728fec09205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('displayname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_displayname'), 'user', ['displayname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_displayname'), table_name='user')
    op.drop_column('user', 'displayname')
    # ### end Alembic commands ###
