"""Added displayname, max players to games

Revision ID: 941586c1203d
Revises: 05bf905537cc
Create Date: 2020-09-25 19:13:34.973202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941586c1203d'
down_revision = '05bf905537cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('display_name', sa.String(length=24), nullable=True))
    op.add_column('game', sa.Column('max_players', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'max_players')
    op.drop_column('game', 'display_name')
    # ### end Alembic commands ###
